# Generated by Django 3.1.2 on 2021-03-01 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.CharField(default='Date', max_length=100),
            preserve_default=False,
        ),
    ]
